spring:
  application:
    name: @project.artifactId@
  cloud:
    client:
      hostname: localhost
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-clientes
          uri: lb://ms-clientes
          predicates:
            - Path=/api/v1/clients/**
        - id: ms-cartoes
          uri: lb://ms-cartoes
          predicates:
            - Path=/api/v1/credit-cards/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: localhost:${server.port}
    preferIpAddress: false
    hostname: localhost
    ipAddr: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: health,info