spring:
  application:
    name: @project.artifactId@

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: false
    hostname: localhost
    ipAddr: 127.0.0.1

feign:
  client:
    name: ms-clientes
    path: /api/v1/clients
  credit-card:
    name: ms-cartoes
    path: /api/v1/credit-cards-client

management:
  endpoints:
    web:
      exposure:
        include: health,info
